
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 12 23:11:24 COT 2015
//----------------------------------------------------

package clases;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Ejecutar = 6;
  public static final int OperadorDothraki = 3;
  public static final int Traduccion = 7;
  public static final int error = 1;
  public static final int OperadorValyrio = 4;
  public static final int FinSentencia = 2;
  public static final int Asigna = 5;
  public static final int EOF = 0;
}

